In [13]:
import numpy as np
from PIL import Image
import os

Task 1

In [14]:
def fahrenheit_to_celsius(f):
    return (f - 32) * 5.0 / 9.0

temperatures_f = np.array([32, 68, 100, 212, 77])
vectorized_conversion = np.vectorize(fahrenheit_to_celsius)
temperatures_c = vectorized_conversion(temperatures_f)
print(temperatures_c)

[  0.          20.          37.77777778 100.          25.        ]


Task 2

In [15]:
def custom_power(base, exponent):
    return base ** exponent

bases = np.array([2, 3, 4, 5])
exponents = np.array([1, 2, 3, 4])
vectorized_power = np.vectorize(custom_power)
results = vectorized_power(bases, exponents)
print(results)

[  2   9  64 625]


Task 3

In [16]:
A = np.array([
    [4, 5, 6],
    [3, -1, 1],
    [2, 1, -2]
])
B = np.array([7, 4, 5])
solution = np.linalg.solve(A, B)
print(solution)

[ 1.7027027   0.62162162 -0.48648649]


Task 4

In [17]:
A_circuit = np.array([
    [10, -2, 3],
    [-2, 8, -1],
    [3, -1, 6]
])
B_circuit = np.array([12, -5, 15])
currents = np.linalg.solve(A_circuit, B_circuit)
print(currents)

[ 0.48963731 -0.2253886   2.21761658]


In [19]:
image_path = "C:/Users/user/Desktop/python-homeworks/lesson-14/homework/birds.jpg"
image = Image.open(image_path)
image_array = np.array(image)
flipped_image = np.flipud(np.fliplr(image_array))
noise = np.random.randint(0, 50, image_array.shape, dtype='uint8')
noisy_image = np.clip(image_array + noise, 0, 255)
brightened_image = image_array.copy()
brightened_image[:, :, 0] = np.clip(brightened_image[:, :, 0] + 40, 0, 255)
masked_image = image_array.copy()
center_x, center_y = masked_image.shape[1] // 2, masked_image.shape[0] // 2
masked_image[center_y - 50:center_y + 50, center_x - 50:center_x + 50] = [0, 0, 0]
output_dir = "images"
os.makedirs(output_dir, exist_ok=True)
Image.fromarray(flipped_image).save(f"{output_dir}/birds_flipped.jpg")
Image.fromarray(noisy_image).save(f"{output_dir}/birds_noisy.jpg")
Image.fromarray(brightened_image).save(f"{output_dir}/birds_brightened.jpg")
Image.fromarray(masked_image).save(f"{output_dir}/birds_masked.jpg")
