In [ ]:
import numpy as np


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a vector with values ranging from 10 to 49.

In [4]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Create a 3x3 matrix with values ranging from 0 to 8.

In [5]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 3x3 identity matrix.

In [6]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values.

In [9]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.76863733 0.00477127 0.82313387]
  [0.78757984 0.01084799 0.02282466]
  [0.40846049 0.35103648 0.33218855]]

 [[0.57663985 0.40218666 0.37657519]
  [0.80113241 0.64741915 0.94517746]
  [0.73117498 0.97811166 0.38598203]]

 [[0.01218752 0.55718988 0.2025907 ]
  [0.62628604 0.32764168 0.31879516]
  [0.5647909  0.02921116 0.16853672]]]


Create a 10x10 array with random values and find the minimum and maximum values.


In [13]:
ten_by_ten = np.random.rand(10, 10)
print("Array:\n", ten_by_ten)
print("Minimum value:", ten_by_ten.min())
print("Maximum value:", ten_by_ten.max())

Array:
 [[0.79333169 0.36771026 0.08812026 0.34858514 0.02968634 0.75671362
  0.7500439  0.12432278 0.88761976 0.23612051]
 [0.10636647 0.08793698 0.49479875 0.05423032 0.78530433 0.48477797
  0.69517409 0.13554607 0.83098815 0.71210442]
 [0.16672498 0.47233785 0.63561267 0.66816395 0.71834087 0.06341666
  0.00505269 0.80588608 0.24410911 0.40387159]
 [0.66905419 0.52094012 0.3709392  0.16140162 0.53497701 0.94945735
  0.19735615 0.70663482 0.13271893 0.94111595]
 [0.04206876 0.53077384 0.63540213 0.05888354 0.53992017 0.63097994
  0.97614406 0.72780935 0.14173788 0.89018525]
 [0.21927256 0.28261154 0.23581184 0.52067854 0.73212358 0.93412581
  0.68800239 0.31117859 0.85987385 0.75469994]
 [0.37822696 0.17509566 0.22443004 0.00537127 0.66675693 0.9028386
  0.55966514 0.42024615 0.25841441 0.99797885]
 [0.65386853 0.08213085 0.05882875 0.50006321 0.78180934 0.96073051
  0.63604834 0.84609436 0.32636778 0.19743394]
 [0.34026223 0.12693418 0.5649184  0.37446012 0.81231736 0.03521132
  0.9

Create a random vector of size 30 and find the mean value.

In [16]:
random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print(random_vector)
print("Mean value:", mean_value)

[0.7251032  0.8427179  0.68521809 0.86564383 0.90527306 0.9812381
 0.45591367 0.95775109 0.85685702 0.64968457 0.59636705 0.97941571
 0.06372087 0.34333914 0.92548024 0.12568013 0.84376325 0.39949744
 0.80774961 0.16297006 0.63974328 0.31595835 0.68094504 0.03630925
 0.75920269 0.76640608 0.97622914 0.76880847 0.69686446 0.9582794 ]
Mean value: 0.6590710067401271


Normalize a 5x5 random matrix.

In [18]:
random_matrix = np.random.random((5, 5))
mean = random_matrix.mean()
std = random_matrix.std()

normalized_matrix = (random_matrix - mean) / std
print(random_matrix)
print("Normalized Matrix: \n", normalized_matrix)

[[0.31241228 0.35307699 0.63377566 0.52734773 0.95181835]
 [0.36031001 0.56264884 0.67219201 0.27087739 0.0740174 ]
 [0.93903692 0.25467892 0.24445198 0.27183077 0.91039603]
 [0.86394334 0.75825557 0.77362325 0.92190771 0.92031154]
 [0.61354246 0.06407571 0.27782312 0.9284801  0.31229077]]
Normalized Matrix: 
 [[-0.81516227 -0.67618296  0.2831578  -0.08057977  1.37012884]
 [-0.65146274  0.04006847  0.41445295 -0.95711564 -1.62992186]
 [ 1.32644588 -1.01247696 -1.04742945 -0.95385726  1.2285602 ]
 [ 1.06979938  0.70859145  0.76111338  1.26790357  1.26244834]
 [ 0.21400702 -1.66389948 -0.93337727  1.29036593 -0.81557756]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [19]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))

result = matrix_5x3.dot(matrix_3x2)
print("5x3 matrix:\n", matrix_5x3)
print("3x2 matrix:\n", matrix_3x2)
print("Result of multiplication:\n", result)

5x3 matrix:
 [[0.67483955 0.54814899 0.61705427]
 [0.91979972 0.74302548 0.24829542]
 [0.55646455 0.6390632  0.73773883]
 [0.49940552 0.91284234 0.0389538 ]
 [0.95267049 0.90557929 0.72524248]]
3x2 matrix:
 [[0.42958027 0.20049105]
 [0.27887641 0.38015021]
 [0.22297787 0.72879642]]
Result of multiplication:
 [[0.58035302 0.79338519]
 [0.65770448 0.64782972]
 [0.58176528 0.8921676 ]
 [0.47779079 0.47553294]
 [0.82350617 1.06381219]]


Create two 3x3 matrices and compute their dot product.

In [20]:
matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))

dot_product = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Dot product:\n", dot_product)

Matrix 1:
 [[0.63036431 0.29528059 0.72342188]
 [0.75185139 0.77409741 0.18213549]
 [0.39043684 0.64460244 0.09919823]]
Matrix 2:
 [[0.13536771 0.10286594 0.61340321]
 [0.40289219 0.93499786 0.41617053]
 [0.17620407 0.04281542 0.84603313]]
Dot product:
 [[0.3317671  0.37190336 1.12159344]
 [0.44574722 0.80891753 0.93743724]
 [0.33003696 0.64711177 0.59168474]]


Given a 4x4 matrix, find its transpose.

In [22]:
matrix_4x4 = np.arange(16).reshape(4, 4)
print("Original:\n", matrix_4x4)

transpose_4x4 = matrix_4x4.T
print("Transposed:\n", transpose_4x4)

Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Transposed:
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


Create a 3x3 matrix and calculate its determinant.

In [25]:
matrix_3x3 = np.random.random((3, 3))
determinant = np.linalg.det(matrix_3x3)
print("3x3 Matrix:\n", matrix_3x3)
print("Determinant:", determinant)

3x3 Matrix:
 [[0.0803566  0.42564991 0.83191549]
 [0.16238446 0.89971744 0.22917106]
 [0.7082304  0.81682002 0.44442288]]
Determinant: -0.36430186094235584


Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

In [26]:
A = np.random.random((3, 4))
B = np.random.random((4, 3))

matrix_product = np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix product:\n", matrix_product)

Matrix A:
 [[0.42708168 0.14236081 0.15641187 0.39222989]
 [0.02644773 0.32128059 0.60921402 0.25834244]
 [0.49790946 0.57337668 0.00200646 0.53652401]]
Matrix B:
 [[0.26304092 0.2429492  0.96745503]
 [0.71297755 0.52004461 0.50115141]
 [0.91022486 0.70291704 0.98078327]
 [0.2237505  0.05281049 0.2219322 ]]
Matrix product:
 [[0.44397162 0.30845155 0.72498123]
 [0.84834868 0.6153758  0.84143863]
 [0.6616491  0.44889263 0.89009339]]


Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.

In [27]:
b = np.array([1, 2, 3])  
x = np.linalg.solve(matrix_3x3, b)
print("Solution for x:", x)

Solution for x: [2.08467191 1.83031812 0.06419897]


Given a 5x5 matrix, find the row-wise and column-wise sums.

In [31]:
random_matrix = np.random.random((5, 5))
row_sums = random_matrix.sum(axis=1)
col_sums = random_matrix.sum(axis=0)
print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)

Row-wise sums: [2.80143909 2.71278835 1.59617724 0.95973927 3.98713598]
Column-wise sums: [1.69376052 2.79067475 2.18545423 2.48392366 2.90346677]
